#include "mainwindow.h" // import file mainwindow.h
#include "helpers.h" // helper functions in here
#include "ui_mainwindow.h"   // generated by uic from mainwindow.ui
#include "models.h" // Product struct definition
#include "paymentdialog.h"
#include "logindialog.h"

#include <QVBoxLayout> // vertical box layout
#include <QKeyEvent> // for handling keyboard events
#include <QHBoxLayout> // horizontal box layout
#include <QCoreApplication>
#include <QWidget> // can hold other widgets
#include <QLabel> // put text
#include <QPushButton> // create buttons
#include <QSqlDatabase> // handle sql connections
#include <QSqlQuery> // use sql commands
#include <QSqlError> // catches sql errors
#include <QFile> // reading and writing files - better compatibility for qt afaik compared to cpp file stream
#include <QTextStream> // format and read human text
#include <QTreeWidget>
#include <QListWidget> // create container for items
#include <QListWidgetItem> // put items into listwidget
#include <QDateTime>
#include <QTimeZone>
#include <QLineEdit> // single line entry, easier to understand that it takes single line of text
#include <QMessageBox> // send a pop up dialog box
#include <QInputDialog> // for handling cash received input
#include <QDir> // navigate file system
#include <QSpinBox> // an input box for numbers specifically
#include <QFileDialog>
#include <QMouseEvent>
#include <QTimer>
#include <QButtonGroup>

// Define roles for QListWidgetItem data
enum ItemDataRole {
    ProductObjectRole = Qt::UserRole, // To store the Product struct
    QuantityRole
};


// *constructor
MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent), ui(new Ui::MainWindow), m_db(new DatabaseManager()) {
    ui->setupUi(this);
    
    initializeDatabase(); // Must open DB before login check

    LoginDialog login(this);
    if (login.exec() != QDialog::Accepted) {
        QTimer::singleShot(0, this, &MainWindow::close);
        return;
    }

    m_currentUserId = login.loggedInUserId();
    m_currentUserRole = login.loggedInRole();

    setupWindowProperties();
    registerCustomTypes();
    loadStylesheets();
    initializeUIStates();
    connectSignalsAndSlots();
    updateResults(""); // Initial search load
}

MainWindow::~MainWindow() {
    delete m_db;
    delete ui;
}

// *window drag & maximize (frameless window helpers)
void MainWindow::mousePressEvent(QMouseEvent *event) {
    if (event->button() == Qt::LeftButton && event->position().y() < 40) {
        m_dragPosition = event->globalPosition().toPoint() - frameGeometry().topLeft();
        event->accept();
    }
}

void MainWindow::mouseMoveEvent(QMouseEvent *event) {
    if (event->buttons() & Qt::LeftButton) {
        if (isMaximized()) {
            toggleMaximize();
            return;
        }
        move(event->globalPosition().toPoint() - m_dragPosition);
        event->accept();
    }
}

void MainWindow::mouseDoubleClickEvent(QMouseEvent *event) {
    if (event->button() == Qt::LeftButton && event->position().y() < 40)
        toggleMaximize();
}

void MainWindow::toggleMaximize() {
    if (isMaximized()) {
        showNormal();
        ui->maxBtn->setText("▢");
        centralWidget()->setStyleSheet("#central { border: 1px solid #d1dce8; }");
    } else {
        showMaximized();
        ui->maxBtn->setText("❐");
        centralWidget()->setStyleSheet("#central { border: none; }");
    }
}

// Private helper methods for constructor decomposition
void MainWindow::setupWindowProperties() {
    QPixmap logo(":/images/app_icon.png");
    ui->iconLabel->setPixmap(logo.scaled(28, 28, Qt::KeepAspectRatio, Qt::SmoothTransformation));
    ui->iconLabel->setText("");

    setWindowTitle("Jupiter Pharmacy");
    setWindowFlags(Qt::FramelessWindowHint);
}

void MainWindow::registerCustomTypes() {
    qRegisterMetaType<Product>();
}

void MainWindow::loadStylesheets() {
    Helpers::loadUI(this);
}

void MainWindow::initializeUIStates() {
    ui->quantityBox->setEnabled(false);
    ui->plusButton->setEnabled(false);
    ui->minusButton->setEnabled(false);
    ui->removeButton->setEnabled(false); // Also disable remove button initially

    if (!ui->billingNavBtn->group()) {
        QButtonGroup* navGroup = new QButtonGroup(this);
        navGroup->addButton(ui->billingNavBtn);
        navGroup->addButton(ui->statsNavBtn);
        navGroup->addButton(ui->historyNavBtn);
        navGroup->setExclusive(true);
    }

    ui->billingNavBtn->setCheckable(true);
    ui->statsNavBtn->setCheckable(true);
    ui->historyNavBtn->setCheckable(true);

    ui->billingNavBtn->setChecked(true);

    // Role-based Feature Gating
    bool isAdmin = (m_currentUserRole == "Admin");
    ui->statsNavBtn->setVisible(isAdmin);
    ui->historyNavBtn->setVisible(isAdmin);
    ui->importBtn->setVisible(isAdmin);
}

void MainWindow::connectSignalsAndSlots() {
    // Search
    connect(ui->searchBox,     &QLineEdit::textChanged,
            this,              &MainWindow::updateResults);
    connect(ui->searchResults, &QListWidget::currentItemChanged,
            this,              &MainWindow::searchSelectionChanged);
    // Allow adding the selected item to cart by pressing Enter on search results
    connect(ui->searchResults, &QListWidget::itemActivated,
            this,              &MainWindow::addToCart);
    connect(ui->addButton,     &QPushButton::clicked,
            this,              &MainWindow::addSelectedSearchItem);

    // Cart
    connect(ui->cartList,       &QListWidget::currentItemChanged,
            this,               &MainWindow::cartSelectionChanged);
    connect(ui->plusButton,     &QPushButton::clicked,
            this,               &MainWindow::increaseQuantity);
    connect(ui->minusButton,    &QPushButton::clicked,
            this,               &MainWindow::decreaseQuantity);
    connect(ui->quantityBox,    qOverload<int>(&QSpinBox::valueChanged),
            this,               &MainWindow::quantityChanged);
    connect(ui->removeButton,   &QPushButton::clicked,
            this,               &MainWindow::removeFromCart);
    connect(ui->clearCartButton,&QPushButton::clicked,
            this,               &MainWindow::clearCart);

    // Checkout
    connect(ui->checkoutButton, &QPushButton::clicked,
            this,               &MainWindow::checkout);
    // Allow adding the first selected item to cart by pressing Enter in the search box
    connect(ui->searchBox,      &QLineEdit::returnPressed,
            this,               &MainWindow::addSelectedSearchItem);

    // Install event filter for searchBox to handle arrow keys
    ui->searchBox->installEventFilter(this);
    ui->cartList->installEventFilter(this);

    // Navigation
    connect(ui->billingNavBtn, &QPushButton::clicked,
            this,              &MainWindow::showBillingPage);
    connect(ui->statsNavBtn,   &QPushButton::clicked,
            this,              &MainWindow::showStatsPage);
    connect(ui->historyNavBtn, &QPushButton::clicked,
            this,              &MainWindow::showHistoryPage);
    connect(ui->importBtn,     &QPushButton::clicked,
            this,              &MainWindow::importNewCsv);
    connect(ui->logoutBtn,     &QPushButton::clicked,
            this,              &MainWindow::handleLogout);

    // Set Shortcuts for quicker operation
    ui->billingNavBtn->setShortcut(QKeySequence("Ctrl+1"));
    ui->statsNavBtn->setShortcut(QKeySequence("Ctrl+2"));
    ui->historyNavBtn->setShortcut(QKeySequence("Ctrl+3"));
    ui->importBtn->setShortcut(QKeySequence("Ctrl+I"));
    ui->checkoutButton->setShortcut(QKeySequence("F5"));
    ui->clearCartButton->setShortcut(QKeySequence("Ctrl+Del"));
    ui->removeButton->setShortcut(QKeySequence("Del"));

    // Title bar
    connect(ui->minBtn,   &QPushButton::clicked, this, &MainWindow::showMinimized);
    connect(ui->maxBtn,   &QPushButton::clicked, this, &MainWindow::toggleMaximize);
    connect(ui->closeBtn, &QPushButton::clicked, this, &MainWindow::close);
}

void MainWindow::initializeDatabase() {
    m_db->open();

    // Ensure the database schema includes columns for the discount feature
    QSqlQuery patchQuery;
    patchQuery.exec("ALTER TABLE transactions ADD COLUMN discount_amount REAL DEFAULT 0.0");
    patchQuery.exec("ALTER TABLE transactions ADD COLUMN discount_type TEXT DEFAULT 'None'");
    patchQuery.exec("ALTER TABLE transactions ADD COLUMN processed_by_id INTEGER DEFAULT 1");

    // Create users table and seed default accounts
    patchQuery.exec("CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT UNIQUE, password TEXT, role TEXT)");
    patchQuery.exec("INSERT OR IGNORE INTO users (username, password, role) VALUES ('admin', 'admin123', 'Admin')");
    patchQuery.exec("INSERT OR IGNORE INTO users (username, password, role) VALUES ('cashier', 'cashier123', 'Cashier')");

    if (m_db->isDatabaseEmpty()) { // Only import CSV if the database is empty
        QString csvPath = "hospital_medicines.csv";
        // Existing logic to find CSV path
        if (!QFile::exists(csvPath)) {
            QString exeDir = QCoreApplication::applicationDirPath();
            QString p1 = exeDir + "/hospital_medicines.csv";
            QString p2 = exeDir + "/../hospital_medicines.csv";
            if (QFile::exists(p1))      csvPath = p1;
            else if (QFile::exists(p2)) csvPath = p2;
        }
        m_db->importCsv(csvPath);
    }
}

// *navigation
void MainWindow::showBillingPage() {
    ui->stackedWidget->setCurrentWidget(ui->billingPage);
}

void MainWindow::showStatsPage() {
    refreshStats();
    ui->stackedWidget->setCurrentWidget(ui->statsPage);
}

void MainWindow::showHistoryPage() {
    ui->historyTree->clear();
    ui->historyTree->setColumnWidth(0, 400); // Give enough space for item names
    
    // Modified SELECT query to include discount_amount and discount_type
    QSqlQuery query;
    if (!query.exec("SELECT id, timestamp, total_amount, discount_amount, discount_type FROM transactions ORDER BY timestamp DESC LIMIT 100")) {
        qDebug() << "History Query Error:" << query.lastError().text();
        return;
    }
    
    while (query.next()) {
        int id = query.value(0).toInt();
        QDateTime dt = query.value(1).toDateTime();
        dt = QDateTime(dt.date(), dt.time(), QTimeZone::utc()); // Re-interpret DB time as UTC
        QString ts = dt.toLocalTime().toString("MMM dd, yyyy - hh:mm AP");
        double total = query.value(2).toDouble(); // This is the final total after discount
        double discountAmount = query.value(3).toDouble();
        QString discountType = query.value(4).toString();

        // Parent Item: The Transaction Summary
        QTreeWidgetItem* orderItem = new QTreeWidgetItem(ui->historyTree);
        orderItem->setText(0, QString("Order #%1  [%2]").arg(id, 5, 10, QChar('0')).arg(ts));
        orderItem->setText(1, QString("₱%1").arg(total, 0, 'f', 2)); // Display final total
        
        // Add discount information as a child item if a discount was applied
        if (discountAmount > 0) {
            QTreeWidgetItem* discountChild = new QTreeWidgetItem(orderItem);
            discountChild->setText(0, QString(" • Discount (%1)").arg(discountType));
            discountChild->setText(1, QString("- ₱%1").arg(discountAmount, 0, 'f', 2));
            QBrush redBrush(QColor("#d9534f"));
            discountChild->setForeground(0, redBrush);
            discountChild->setForeground(1, redBrush);
        }
        
        // Emphasize the parent row
        QFont boldFont;
        boldFont.setBold(true);
        orderItem->setFont(0, boldFont);
        orderItem->setFont(1, boldFont);

        // Sub-query: Get individual items for this order
        QSqlQuery itemQuery;
        itemQuery.prepare("SELECT p.item_name, ti.quantity, ti.price FROM transaction_items ti "
                          "JOIN products p ON ti.product_id = p.item_id WHERE ti.transaction_id = :id");
        itemQuery.bindValue(":id", id);
        
        if (itemQuery.exec()) {
            while (itemQuery.next()) {
                QTreeWidgetItem* child = new QTreeWidgetItem(orderItem);
                QString name = itemQuery.value(0).toString();
                int qty = itemQuery.value(1).toInt();
                double price = itemQuery.value(2).toDouble();
                
                child->setText(0, QString(" • %1 (x%2)").arg(name).arg(qty));
                child->setText(1, QString("₱%1").arg(price * qty, 0, 'f', 2));
                child->setForeground(0, QBrush(QColor("#6a8fb5"))); // Subtle blue for items
            }
        }
    }
    
    ui->historyTree->expandAll(); // Automatically expand all orders to show discounts and items
    ui->stackedWidget->setCurrentWidget(ui->historyPage);
}

void MainWindow::handleLogout() {
    this->hide(); // Hide the window for security during the switch

    LoginDialog login(this);
    login.setWindowTitle("Switch User");
    
    if (login.exec() == QDialog::Accepted) {
        clearCart(); // Clear current cart for the new user session
        m_currentUserId = login.loggedInUserId();
        m_currentUserRole = login.loggedInRole();
        
        initializeUIStates(); // Refresh UI gating (History, Stats, etc.)
        showBillingPage();    // Return to billing
        updateResults("");    // Refresh search results
        this->show();         // Reveal window for the new user
    } else {
        this->close();        // Exit the app if the new login is cancelled
    }
}

// *search
void MainWindow::searchSelectionChanged(QListWidgetItem* current, QListWidgetItem*) {
    ui->addButton->setEnabled(current != nullptr);
}

void MainWindow::addSelectedSearchItem() {
    QListWidgetItem* current = ui->searchResults->currentItem();
    if (current)
        addToCart(current);
}

void MainWindow::updateResults(const QString &text) {
    ui->searchResults->clear();
    QString trimmed = text.trimmed();

    QList<Product> products = m_db->searchProducts(trimmed);

    for (const Product& product : products) {
        QListWidgetItem* item = new QListWidgetItem(product.toSearchString());
        item->setData(ProductObjectRole, QVariant::fromValue(product));
        ui->searchResults->addItem(item);
    }

    // Automatically select the first item if results are available
    if (ui->searchResults->count() > 0) {
        ui->searchResults->setCurrentRow(0);
    }
}


// *cart
void MainWindow::updateCartItemDisplay(QListWidgetItem* item) {
    Product product = item->data(ProductObjectRole).value<Product>();
    int quantity = item->data(QuantityRole).toInt();
    item->setText(product.toCartString(quantity));
}

void MainWindow::addToCart(QListWidgetItem* item) {
    if (!item) return;

    Product product = item->data(ProductObjectRole).value<Product>();
    int stock = product.stock;

    if (stock <= 0) {
        QMessageBox::warning(this, "Out of stock",
                             "This item is out of stock and cannot be added to the cart.");
        return;
    }

    // *check if the item is already in the cart
    QListWidgetItem* existing = nullptr;
    for (int i = 0; i < ui->cartList->count(); ++i) {
        QListWidgetItem* it = ui->cartList->item(i);
        if (it->data(ProductObjectRole).value<Product>().id == product.id) {
            existing = it;
            break;
        }
    }

    if (existing) {
        int quantity = existing->data(QuantityRole).toInt() + 1;
        if (quantity > stock) {
            QMessageBox::warning(this, "Stock limit",
                                 QString("Only %1 unit(s) available.").arg(stock));
            return;
        }
        existing->setData(QuantityRole, quantity);
        updateCartItemDisplay(existing);
        ui->cartList->setCurrentItem(existing);
    } else {
        QListWidgetItem* cartItem = new QListWidgetItem();
        // Store the Product object and initial quantity
        cartItem->setData(ProductObjectRole, QVariant::fromValue(product));
        cartItem->setData(QuantityRole, 1);
        updateCartItemDisplay(cartItem);
        ui->cartList->addItem(cartItem);
        ui->cartList->setCurrentItem(cartItem);
    }
    updateCartTotals();
}

void MainWindow::cartSelectionChanged(QListWidgetItem* current, QListWidgetItem*) {
    bool hasItem = current != nullptr;
    ui->quantityBox->setEnabled(hasItem);
    ui->plusButton->setEnabled(hasItem);
    ui->minusButton->setEnabled(hasItem);
    ui->removeButton->setEnabled(hasItem);

    if (hasItem)
        ui->quantityBox->setValue(current->data(QuantityRole).toInt()); // Retrieve quantity
}

void MainWindow::increaseQuantity() {
    QListWidgetItem* current = ui->cartList->currentItem();
    if (!current) return;
    
    Product product = current->data(ProductObjectRole).value<Product>();
    int stock = product.stock; // Use stock from the Product object
    int quantity = current->data(QuantityRole).toInt() + 1;
    if (quantity > stock) {
        QMessageBox::warning(this, "Stock limit",
                             QString("Only %1 unit(s) available.").arg(stock));
        return;
    }
    current->setData(QuantityRole, quantity);
    updateCartItemDisplay(current);
    ui->quantityBox->setValue(quantity);
    updateCartTotals();
}

void MainWindow::decreaseQuantity() {
    QListWidgetItem* current = ui->cartList->currentItem();
    if (!current) return;

    int quantity = current->data(QuantityRole).toInt() - 1;
    if (quantity <= 0) {
        delete current;
        updateCartTotals();
        return;
    }
    current->setData(QuantityRole, quantity);
    updateCartItemDisplay(current);
    ui->quantityBox->setValue(quantity);
    updateCartTotals();
}

void MainWindow::quantityChanged(int value) {
    QListWidgetItem* current = ui->cartList->currentItem();
    if (!current) return;

    Product product = current->data(ProductObjectRole).value<Product>();
    int stock = product.stock; // Use stock from the Product object
    if (value > stock) {
        QMessageBox::warning(this, "Stock limit",
                             QString("Only %1 unit(s) available.").arg(stock));
        ui->quantityBox->setValue(stock);
        value = stock;
    }
    current->setData(QuantityRole, value);
    updateCartItemDisplay(current);
    updateCartTotals();
}

void MainWindow::updateCartTotals() {
    double total = 0.0;
    for (int i = 0; i < ui->cartList->count(); ++i) {
        QListWidgetItem* item = ui->cartList->item(i);
        Product product = item->data(ProductObjectRole).value<Product>();
        total += product.price * item->data(QuantityRole).toInt();
    }
    ui->totalLabel->setText(QString("Total: ₱%1").arg(total, 0, 'f', 2));
}

void MainWindow::removeFromCart() {
    QListWidgetItem* current = ui->cartList->currentItem();
    if (current) {
        delete current;
        updateCartTotals();
    }
}

void MainWindow::clearCart() {
    ui->cartList->clear();
    updateCartTotals();
    ui->quantityBox->setEnabled(false);
    ui->plusButton->setEnabled(false);
    ui->minusButton->setEnabled(false);
    ui->removeButton->setEnabled(false);
}


// *checkout
void MainWindow::checkout() {
    if (ui->cartList->count() == 0) {
        QMessageBox::information(this, "Checkout", "Cart is empty.");
        return;
    }

    double originalTotal = 0.0;
    for (int i = 0; i < ui->cartList->count(); ++i) {
        QListWidgetItem* item = ui->cartList->item(i);
        Product product = item->data(ProductObjectRole).value<Product>();
        originalTotal += product.price * item->data(QuantityRole).toInt();
    }

    PaymentDialog diag(originalTotal, m_currentUserRole, this);
    if (diag.exec() != QDialog::Accepted) {
        return;
    }

    double received = diag.getReceivedAmount();
    double finalTotal = diag.getFinalTotal();
    double discountAmount = diag.getDiscountAmount();
    QString discountType = diag.getDiscountType();

    if (received < finalTotal) {
        QMessageBox::warning(this, "Insufficient Payment",
                             QString("The amount received (₱%1) is less than the total due (₱%2).").arg(received, 0, 'f', 2).arg(finalTotal, 0, 'f', 2));
        return;
    }

    double change = received - finalTotal;

    // Save Transaction to Database
    QSqlQuery tQuery;
    tQuery.prepare("INSERT INTO transactions (total_amount, received, change_amount, discount_amount, discount_type, processed_by_id) VALUES (:t, :r, :c, :da, :dt, :uid)");
    tQuery.bindValue(":t", finalTotal); // Store the final discounted total
    tQuery.bindValue(":r", received);
    tQuery.bindValue(":c", change);
    tQuery.bindValue(":da", discountAmount);
    tQuery.bindValue(":dt", discountType);
    tQuery.bindValue(":uid", m_currentUserId);

    if (tQuery.exec()) {
        qlonglong transactionId = tQuery.lastInsertId().toLongLong();
        QSqlQuery itemQuery;
        itemQuery.prepare("INSERT INTO transaction_items (transaction_id, product_id, quantity, price) "
                          "VALUES (:tid, :pid, :q, :p)");

        for (int i = 0; i < ui->cartList->count(); ++i) {
            QListWidgetItem* item = ui->cartList->item(i);
            Product product = item->data(ProductObjectRole).value<Product>();
            itemQuery.bindValue(":tid", transactionId);
            itemQuery.bindValue(":pid", product.id);
            itemQuery.bindValue(":q", item->data(QuantityRole).toInt());
            itemQuery.bindValue(":p", product.price);
            itemQuery.exec();
        }

        QMessageBox::information(this, "Sale Complete", QString("Original Total: ₱%1\nDiscount Applied: ₱%2 (%3)\nFinal Total Due: ₱%4\nAmount Received: ₱%5\nChange: ₱%6")
                                 .arg(originalTotal, 0, 'f', 2)
                                 .arg(discountAmount, 0, 'f', 2)
                                 .arg(discountType)
                                 .arg(finalTotal, 0, 'f', 2)
                                 .arg(received, 0, 'f', 2)
                                 .arg(change, 0, 'f', 2));
    }

    updateStock();
    ui->cartList->clear();
    updateCartTotals();
    ui->quantityBox->setEnabled(false);
    ui->plusButton->setEnabled(false);
    ui->minusButton->setEnabled(false);
    ui->removeButton->setEnabled(false);
    updateResults(ui->searchBox->text());
}

void MainWindow::updateStock() {
    for (int i = 0; i < ui->cartList->count(); ++i) {
        QListWidgetItem* item = ui->cartList->item(i);
        Product product = item->data(ProductObjectRole).value<Product>();
        int soldQuantity = item->data(QuantityRole).toInt();
        if (!m_db->updateStock(product.id, soldQuantity)) {
            qWarning() << "Failed to update stock for product:" << product.id;
        }
    }
}


// *statistics
void MainWindow::refreshStats()
{
    int totalProducts = 0;
    double totalValue = 0.0;
    m_db->getInventorySummary(totalProducts, totalValue);
    ui->totalProductsLabel->setText(QString::number(totalProducts));
    ui->totalValueLabel->setText(QString("₱%1").arg(totalValue, 0, 'f', 2));

    ui->lowStockList->clear();
    QList<Product> lowStockProducts = m_db->getLowStockItems();
    for (const Product& product : lowStockProducts) {
        QListWidgetItem* item = new QListWidgetItem(
            QString("⚠️ %1 (ID: %2) — Only %3 left").arg(product.name, product.id).arg(product.stock));
        if (product.stock == 0)
            item->setForeground(Qt::red);
        ui->lowStockList->addItem(item);
    }
}


// *import
void MainWindow::importNewCsv()
{
    QString fileName = QFileDialog::getOpenFileName(
        this, "Import Medicines", "", "CSV Files (*.csv)");
    if (!fileName.isEmpty()) {
        m_db->importCsv(fileName); // Use the DatabaseManager to import
        updateResults(ui->searchBox->text());
        QMessageBox::information(this, "Success", "Database updated successfully.");
    }
}

bool MainWindow::eventFilter(QObject *obj, QEvent *event) {
    if (event->type() == QEvent::KeyPress) {
        QKeyEvent *keyEvent = static_cast<QKeyEvent *>(event);

        // Focus is on Search Box
        if (obj == ui->searchBox) {
            if (keyEvent->key() == Qt::Key_Up || keyEvent->key() == Qt::Key_Down) {
                int count = ui->searchResults->count();
                if (count > 0) {
                    int row = ui->searchResults->currentRow();
                    if (keyEvent->key() == Qt::Key_Up) row = (row > 0) ? row - 1 : 0;
                    else row = (row < count - 1) ? row + 1 : count - 1;
                    ui->searchResults->setCurrentRow(row);
                    return true;
                }
            } else if (keyEvent->key() == Qt::Key_Right) {
                ui->cartList->setFocus();
                if (ui->cartList->count() > 0 && !ui->cartList->currentItem())
                    ui->cartList->setCurrentRow(0);
                return true;
            }
        }
        // Focus is on Cart List
        else if (obj == ui->cartList) {
            if (keyEvent->key() == Qt::Key_Left) {
                ui->searchBox->setFocus();
                return true;
            }
        }
    }
    return QMainWindow::eventFilter(obj, event);
}
