#include "mainwindow.h" // import file mainwindow.h
#include "helpers.h" // helper functions in here
#include "ui_mainwindow.h"   // generated by uic from mainwindow.ui
#include "models.h" // Product struct definition

#include <QVBoxLayout> // vertical box layout
#include <QHBoxLayout> // horizontal box layout
#include <QCoreApplication>
#include <QWidget> // can hold other widgets
#include <QLabel> // put text
#include <QPushButton> // create buttons
#include <QSqlDatabase> // handle sql connections
#include <QSqlQuery> // use sql commands
#include <QSqlError> // catches sql errors
#include <QFile> // reading and writing files - better compatibility for qt afaik compared to cpp file stream
#include <QTextStream> // format and read human text
#include <QListWidget> // create container for items
#include <QListWidgetItem> // put items into listwidget
#include <QLineEdit> // single line entry, easier to understand that it takes single line of text
#include <QMessageBox> // send a pop up dialog box
#include <QDir> // navigate file system
#include <QSpinBox> // an input box for numbers specifically
#include <QFileDialog>
#include <QMouseEvent>

// Define roles for QListWidgetItem data
enum ItemDataRole {
    ProductObjectRole = Qt::UserRole, // To store the Product struct
    QuantityRole
};



// *constructor
MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent)
    , ui(new Ui::MainWindow)
{
    ui->setupUi(this);

    QPixmap logo(":/images/app_icon.png");
    ui->iconLabel->setPixmap(logo.scaled(28, 28, Qt::KeepAspectRatio, Qt::SmoothTransformation));
    ui->iconLabel->setText("");

    setWindowTitle("Jupiter Pharmacy"); // window title
    setWindowFlags(Qt::FramelessWindowHint); // remove title bar

    // Register Product struct for QVariant usage
    qRegisterMetaType<Product>();

    // *load ui
    Helpers::loadUI(this);

    // *initial widget states
    ui->quantityBox->setEnabled(false);
    ui->plusButton->setEnabled(false);
    ui->minusButton->setEnabled(false);

    // *signal/slot connections
    // *search
    connect(ui->searchBox,     &QLineEdit::textChanged,
            this,              &MainWindow::updateResults);
    connect(ui->searchResults, &QListWidget::itemDoubleClicked,
            this,              &MainWindow::addToCart);
    connect(ui->searchResults, &QListWidget::currentItemChanged,
            this,              &MainWindow::searchSelectionChanged);
    connect(ui->addButton,     &QPushButton::clicked,
            this,              &MainWindow::addSelectedSearchItem);

    // *cart
    connect(ui->cartList,       &QListWidget::currentItemChanged,
            this,               &MainWindow::cartSelectionChanged);
    connect(ui->plusButton,     &QPushButton::clicked,
            this,               &MainWindow::increaseQuantity);
    connect(ui->minusButton,    &QPushButton::clicked,
            this,               &MainWindow::decreaseQuantity);
    connect(ui->quantityBox,    qOverload<int>(&QSpinBox::valueChanged),
            this,               &MainWindow::quantityChanged);
    connect(ui->removeButton,   &QPushButton::clicked,
            this,               &MainWindow::removeFromCart);
    connect(ui->clearCartButton,&QPushButton::clicked,
            this,               &MainWindow::clearCart);

    // *checkout
    connect(ui->checkoutButton, &QPushButton::clicked,
            this,               &MainWindow::checkout);

    // *navigation
    connect(ui->billingNavBtn, &QPushButton::clicked,
            this,              &MainWindow::showBillingPage);
    connect(ui->statsNavBtn,   &QPushButton::clicked,
            this,              &MainWindow::showStatsPage);
    connect(ui->importBtn,     &QPushButton::clicked,
            this,              &MainWindow::importNewCsv);

    // *title bar
    connect(ui->minBtn,   &QPushButton::clicked, this, &MainWindow::showMinimized);
    connect(ui->maxBtn,   &QPushButton::clicked, this, &MainWindow::toggleMaximize);
    connect(ui->closeBtn, &QPushButton::clicked, this, &MainWindow::close);

    // *database
    QString csvPath = "hospital_medicines.csv";
    if (!QFile::exists(csvPath)) {
        QString exeDir = QCoreApplication::applicationDirPath();
        QString p1 = exeDir + "/hospital_medicines.csv";
        QString p2 = exeDir + "/../hospital_medicines.csv";
        if (QFile::exists(p1))      csvPath = p1;
        else if (QFile::exists(p2)) csvPath = p2;
    }

    db = Helpers::openDatabase();
    Helpers::importCsvToDatabase(csvPath, db);

    // *initial search load
    updateResults("");
}

MainWindow::~MainWindow()
{
    delete ui;
}


// *window drag & maximize (frameless window helpers)
void MainWindow::mousePressEvent(QMouseEvent *event)
{
    if (event->button() == Qt::LeftButton && event->position().y() < 40) {
        m_dragPosition = event->globalPosition().toPoint() - frameGeometry().topLeft();
        event->accept();
    }
}

void MainWindow::mouseMoveEvent(QMouseEvent *event)
{
    if (event->buttons() & Qt::LeftButton) {
        if (isMaximized()) {
            toggleMaximize();
            return;
        }
        move(event->globalPosition().toPoint() - m_dragPosition);
        event->accept();
    }
}

void MainWindow::mouseDoubleClickEvent(QMouseEvent *event)
{
    if (event->button() == Qt::LeftButton && event->position().y() < 40)
        toggleMaximize();
}

void MainWindow::toggleMaximize()
{
    if (isMaximized()) {
        showNormal();
        ui->maxBtn->setText("▢");
        centralWidget()->setStyleSheet("#central { border: 1px solid #d1dce8; }");
    } else {
        showMaximized();
        ui->maxBtn->setText("❐");
        centralWidget()->setStyleSheet("#central { border: none; }");
    }
}


// *navigation
void MainWindow::showBillingPage()
{
    ui->stackedWidget->setCurrentWidget(ui->billingPage);
}

void MainWindow::showStatsPage()
{
    refreshStats();
    ui->stackedWidget->setCurrentWidget(ui->statsPage);
}


// *search
void MainWindow::searchSelectionChanged(QListWidgetItem* current, QListWidgetItem*)
{
    ui->addButton->setEnabled(current != nullptr);
}

void MainWindow::addSelectedSearchItem()
{
    QListWidgetItem* current = ui->searchResults->currentItem();
    if (current)
        addToCart(current);
}

void MainWindow::updateResults(const QString &text)
{
    ui->searchResults->clear();
    QString trimmed = text.trimmed();

    QSqlQuery query(db);
    if (trimmed.isEmpty()) {
        query.prepare(R"(
            SELECT item_id, item_name, description, retail_price, stock
            FROM products
            LIMIT 999
        )");
    } else {
        query.prepare(R"(
            SELECT item_id, item_name, description, retail_price, stock
            FROM products
            WHERE item_name LIKE :term1
               OR description LIKE :term2
               OR item_id    LIKE :term3
            LIMIT 999
        )");
        QString match = "%" + trimmed + "%";
        query.bindValue(":term1", match);
        query.bindValue(":term2", match);
        query.bindValue(":term3", match);
    }

    if (!query.exec()) {
        qWarning() << "Search query failed:" << query.lastError().text();
        return;
    }

    while (query.next()) {
        QString id    = query.value(0).toString();
        QString name  = query.value(1).toString();
        QString desc  = query.value(2).toString();
        double  price = query.value(3).toDouble();
        int     stock = query.value(4).toInt();

        Product product = {id, name, desc, price, stock};

        QString itemText = QString("%1 | %2 | %3 | P%4 | stock:%5")
                               .arg(id, name, desc)
                               .arg(price, 0, 'f', 2)
                               .arg(stock);

        QListWidgetItem* item = new QListWidgetItem(itemText);
        // Store the entire Product object in the item's data
        item->setData(ProductObjectRole, QVariant::fromValue(product));

        ui->searchResults->addItem(item);
    }
}


// *cart
void MainWindow::updateCartItemDisplay(QListWidgetItem* item)
{
    Product product = item->data(ProductObjectRole).value<Product>();
    int quantity = item->data(QuantityRole).toInt();

    item->setText(QString("%1 x%2 — ₱%3 each — stock:%4 — ID:%5")
                      .arg(product.name).arg(quantity)
                      .arg(product.price, 0, 'f', 2)
                      .arg(product.stock).arg(product.id));
}

void MainWindow::addToCart(QListWidgetItem* item)
{
    if (!item) return;

    Product product = item->data(ProductObjectRole).value<Product>();
    int stock = product.stock;

    if (stock <= 0) {
        QMessageBox::warning(this, "Out of stock",
                             "This item is out of stock and cannot be added to the cart.");
        return;
    }

    // *check if the item is already in the cart
    QListWidgetItem* existing = nullptr;
    for (int i = 0; i < ui->cartList->count(); ++i) {
        QListWidgetItem* it = ui->cartList->item(i);
        if (it->data(ProductObjectRole).value<Product>().id == product.id) {
            existing = it;
            break;
        }
    }

    if (existing) {
        int quantity = existing->data(QuantityRole).toInt() + 1;
        if (quantity > stock) {
            QMessageBox::warning(this, "Stock limit",
                                 QString("Only %1 unit(s) available.").arg(stock));
            return;
        }
        existing->setData(QuantityRole, quantity);
        updateCartItemDisplay(existing);
    } else {
        QListWidgetItem* cartItem = new QListWidgetItem();
        // Store the Product object and initial quantity
        cartItem->setData(ProductObjectRole, QVariant::fromValue(product));
        cartItem->setData(QuantityRole, 1);
        updateCartItemDisplay(cartItem);
        ui->cartList->addItem(cartItem);
    }
    updateCartTotals();
}

void MainWindow::cartSelectionChanged(QListWidgetItem* current, QListWidgetItem*)
{
    bool hasItem = current != nullptr;
    ui->quantityBox->setEnabled(hasItem);
    ui->plusButton->setEnabled(hasItem);
    ui->minusButton->setEnabled(hasItem);
    ui->removeButton->setEnabled(hasItem);

    if (hasItem)
        ui->quantityBox->setValue(current->data(QuantityRole).toInt()); // Retrieve quantity
}

void MainWindow::increaseQuantity()
{
    QListWidgetItem* current = ui->cartList->currentItem();
    if (!current) return;
    
    Product product = current->data(ProductObjectRole).value<Product>();
    int stock = product.stock; // Use stock from the Product object
    int quantity = current->data(QuantityRole).toInt() + 1;
    if (quantity > stock) {
        QMessageBox::warning(this, "Stock limit",
                             QString("Only %1 unit(s) available.").arg(stock));
        return;
    }
    current->setData(QuantityRole, quantity);
    updateCartItemDisplay(current);
    ui->quantityBox->setValue(quantity);
    updateCartTotals();
}

void MainWindow::decreaseQuantity()
{
    QListWidgetItem* current = ui->cartList->currentItem();
    if (!current) return;

    int quantity = current->data(QuantityRole).toInt() - 1;
    if (quantity <= 0) {
        delete current;
        updateCartTotals();
        return;
    }
    current->setData(QuantityRole, quantity);
    updateCartItemDisplay(current);
    ui->quantityBox->setValue(quantity);
    updateCartTotals();
}

void MainWindow::quantityChanged(int value)
{
    QListWidgetItem* current = ui->cartList->currentItem();
    if (!current) return;

    Product product = current->data(ProductObjectRole).value<Product>();
    int stock = product.stock; // Use stock from the Product object
    if (value > stock) {
        QMessageBox::warning(this, "Stock limit",
                             QString("Only %1 unit(s) available.").arg(stock));
        ui->quantityBox->setValue(stock);
        value = stock;
    }
    current->setData(QuantityRole, value);
    updateCartItemDisplay(current);
    updateCartTotals();
}

void MainWindow::updateCartTotals()
{
    double total = 0.0;
    for (int i = 0; i < ui->cartList->count(); ++i) {
        QListWidgetItem* item = ui->cartList->item(i);
        Product product = item->data(ProductObjectRole).value<Product>();
        total += product.price * item->data(QuantityRole).toInt();
    }
    ui->totalLabel->setText(QString("Total: ₱%1").arg(total, 0, 'f', 2));
}

void MainWindow::removeFromCart()
{
    QListWidgetItem* current = ui->cartList->currentItem();
    if (current) {
        delete current;
        updateCartTotals();
    }
}

void MainWindow::clearCart()
{
    ui->cartList->clear();
    updateCartTotals();
    ui->quantityBox->setEnabled(false);
    ui->plusButton->setEnabled(false);
    ui->minusButton->setEnabled(false);
    ui->removeButton->setEnabled(false);
}


// *checkout
void MainWindow::checkout()
{
    if (ui->cartList->count() == 0) {
        QMessageBox::information(this, "Checkout", "Cart is empty.");
        return;
    }

    double total = 0.0;
    for (int i = 0; i < ui->cartList->count(); ++i) {
        QListWidgetItem* item = ui->cartList->item(i);
        Product product = item->data(ProductObjectRole).value<Product>();
        total += product.price * item->data(QuantityRole).toInt();
    }

    QMessageBox::information(this, "Checkout",
                             QString("Total due: ₱%1\nSale complete.").arg(total, 0, 'f', 2));

    updateStock();
    ui->cartList->clear();
    updateCartTotals();
    ui->quantityBox->setEnabled(false);
    ui->plusButton->setEnabled(false);
    ui->minusButton->setEnabled(false);
    ui->removeButton->setEnabled(false);
    updateResults(ui->searchBox->text());
}

void MainWindow::updateStock()
{
    QSqlQuery update(db);
    update.prepare("UPDATE products SET stock = stock - :sold WHERE item_id = :id");

    for (int i = 0; i < ui->cartList->count(); ++i) {
        QListWidgetItem* item = ui->cartList->item(i);
        Product product = item->data(ProductObjectRole).value<Product>();
        update.bindValue(":sold", item->data(QuantityRole).toInt()); // Quantity sold
        update.bindValue(":id",   product.id); // Product ID
        if (!update.exec())
            qWarning() << "Failed to update stock:" << update.lastError().text();
    }
}


// *statistics
void MainWindow::refreshStats()
{
    QSqlQuery query(db);

    if (query.exec("SELECT COUNT(*), SUM(retail_price * stock) FROM products") && query.next()) {
        ui->totalProductsLabel->setText(query.value(0).toString());
        double totalVal = query.value(1).toDouble();
        ui->totalValueLabel->setText(QString("₱%1").arg(totalVal, 0, 'f', 2));
    }

    ui->lowStockList->clear();
    query.prepare(
        "SELECT item_name, stock, item_id FROM products "
        "WHERE stock < 10 ORDER BY stock ASC");
    if (query.exec()) {
        while (query.next()) {
            QString name  = query.value(0).toString();
            int     stock = query.value(1).toInt();
            QString id    = query.value(2).toString();

            QListWidgetItem* item = new QListWidgetItem(
                QString("⚠️ %1 (ID: %2) — Only %3 left").arg(name, id).arg(stock));
            if (stock == 0)
                item->setForeground(Qt::red);
            ui->lowStockList->addItem(item);
        }
    }
}


// *import
void MainWindow::importNewCsv()
{
    QString fileName = QFileDialog::getOpenFileName(
        this, "Import Medicines", "", "CSV Files (*.csv)");
    if (!fileName.isEmpty()) {
        Helpers::importCsvToDatabase(fileName, db);
        updateResults(ui->searchBox->text());
        QMessageBox::information(this, "Success", "Database updated successfully.");
    }
}
