#include "mainwindow.h"
#include "helpers.h"
#include "ui_mainwindow.h"   // generated by uic from mainwindow.ui

#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QCoreApplication>
#include <QWidget>
#include <QLabel>
#include <QPushButton>
#include <QSqlDatabase>
#include <QSqlQuery>
#include <QSqlError>
#include <QFile>
#include <QTextStream>
#include <QListWidget>
#include <QListWidgetItem>
#include <QLineEdit>
#include <QMessageBox>
#include <QDir>
#include <QSpinBox>
#include <QFileDialog>
#include <QMouseEvent>

// ─────────────────────────────────────────────────────────────────────────────
// Constructor
// ─────────────────────────────────────────────────────────────────────────────
MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent)
    , ui(new Ui::MainWindow)
{
    ui->setupUi(this);

    setWindowTitle("Jupiter Drugstore");
    setWindowFlags(Qt::FramelessWindowHint);

    // Apply stylesheet from resources
    Helpers::loadUI(this);

    // ── initial widget states ────────────────────────────────────────────────
    ui->quantityBox->setEnabled(false);
    ui->plusButton->setEnabled(false);
    ui->minusButton->setEnabled(false);

    // ── signal/slot connections ──────────────────────────────────────────────
    // search
    connect(ui->searchBox,     &QLineEdit::textChanged,
            this,              &MainWindow::updateResults);
    connect(ui->searchResults, &QListWidget::itemDoubleClicked,
            this,              &MainWindow::addToCart);
    connect(ui->searchResults, &QListWidget::currentItemChanged,
            this,              &MainWindow::searchSelectionChanged);
    connect(ui->addButton,     &QPushButton::clicked,
            this,              &MainWindow::addSelectedSearchItem);

    // cart
    connect(ui->cartList,       &QListWidget::currentItemChanged,
            this,               &MainWindow::cartSelectionChanged);
    connect(ui->plusButton,     &QPushButton::clicked,
            this,               &MainWindow::increaseQuantity);
    connect(ui->minusButton,    &QPushButton::clicked,
            this,               &MainWindow::decreaseQuantity);
    connect(ui->quantityBox,    qOverload<int>(&QSpinBox::valueChanged),
            this,               &MainWindow::quantityChanged);
    connect(ui->removeButton,   &QPushButton::clicked,
            this,               &MainWindow::removeFromCart);
    connect(ui->clearCartButton,&QPushButton::clicked,
            this,               &MainWindow::clearCart);

    // checkout
    connect(ui->checkoutButton, &QPushButton::clicked,
            this,               &MainWindow::checkout);

    // navigation
    connect(ui->billingNavBtn, &QPushButton::clicked,
            this,              &MainWindow::showBillingPage);
    connect(ui->statsNavBtn,   &QPushButton::clicked,
            this,              &MainWindow::showStatsPage);
    connect(ui->importBtn,     &QPushButton::clicked,
            this,              &MainWindow::importNewCsv);

    // title bar
    connect(ui->minBtn,   &QPushButton::clicked, this, &MainWindow::showMinimized);
    connect(ui->maxBtn,   &QPushButton::clicked, this, &MainWindow::toggleMaximize);
    connect(ui->closeBtn, &QPushButton::clicked, this, &MainWindow::close);

    // ── database ─────────────────────────────────────────────────────────────
    QString csvPath = "hospital_medicines.csv";
    if (!QFile::exists(csvPath)) {
        QString exeDir = QCoreApplication::applicationDirPath();
        QString p1 = exeDir + "/hospital_medicines.csv";
        QString p2 = exeDir + "/../hospital_medicines.csv";
        if (QFile::exists(p1))      csvPath = p1;
        else if (QFile::exists(p2)) csvPath = p2;
    }

    db = Helpers::openDatabase();
    Helpers::importCsvToDatabase(csvPath, db);

    // ── initial search load ───────────────────────────────────────────────────
    updateResults("");
}

MainWindow::~MainWindow()
{
    delete ui;
}

// ─────────────────────────────────────────────────────────────────────────────
// Window drag & maximize (frameless window helpers)
// ─────────────────────────────────────────────────────────────────────────────
void MainWindow::mousePressEvent(QMouseEvent *event)
{
    if (event->button() == Qt::LeftButton && event->position().y() < 40) {
        m_dragPosition = event->globalPosition().toPoint() - frameGeometry().topLeft();
        event->accept();
    }
}

void MainWindow::mouseMoveEvent(QMouseEvent *event)
{
    if (event->buttons() & Qt::LeftButton) {
        if (isMaximized()) {
            toggleMaximize();
            return;
        }
        move(event->globalPosition().toPoint() - m_dragPosition);
        event->accept();
    }
}

void MainWindow::mouseDoubleClickEvent(QMouseEvent *event)
{
    if (event->button() == Qt::LeftButton && event->position().y() < 40)
        toggleMaximize();
}

void MainWindow::toggleMaximize()
{
    if (isMaximized()) {
        showNormal();
        ui->maxBtn->setText("▢");
        centralWidget()->setStyleSheet("#central { border: 1px solid #dcdcdc; }");
    } else {
        showMaximized();
        ui->maxBtn->setText("❐");
        centralWidget()->setStyleSheet("#central { border: none; }");
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Navigation
// ─────────────────────────────────────────────────────────────────────────────
void MainWindow::showBillingPage()
{
    ui->stackedWidget->setCurrentWidget(ui->billingPage);
}

void MainWindow::showStatsPage()
{
    refreshStats();
    ui->stackedWidget->setCurrentWidget(ui->statsPage);
}

// ─────────────────────────────────────────────────────────────────────────────
// Search
// ─────────────────────────────────────────────────────────────────────────────
void MainWindow::searchSelectionChanged(QListWidgetItem* current, QListWidgetItem*)
{
    ui->addButton->setEnabled(current != nullptr);
}

void MainWindow::addSelectedSearchItem()
{
    QListWidgetItem* current = ui->searchResults->currentItem();
    if (current)
        addToCart(current);
}

void MainWindow::updateResults(const QString &text)
{
    ui->searchResults->clear();
    QString trimmed = text.trimmed();

    QSqlQuery query(db);
    if (trimmed.isEmpty()) {
        query.prepare(R"(
            SELECT item_id, item_name, description, retail_price, stock
            FROM products
            LIMIT 999
        )");
    } else {
        query.prepare(R"(
            SELECT item_id, item_name, description, retail_price, stock
            FROM products
            WHERE item_name LIKE :term1
               OR description LIKE :term2
               OR item_id    LIKE :term3
            LIMIT 999
        )");
        QString match = "%" + trimmed + "%";
        query.bindValue(":term1", match);
        query.bindValue(":term2", match);
        query.bindValue(":term3", match);
    }

    if (!query.exec()) {
        qWarning() << "Search query failed:" << query.lastError().text();
        return;
    }

    while (query.next()) {
        QString id    = query.value(0).toString();
        QString name  = query.value(1).toString();
        QString desc  = query.value(2).toString();
        double  price = query.value(3).toDouble();
        int     stock = query.value(4).toInt();

        QString itemText = QString("%1 | %2 | %3 | P%4 | stock:%5")
                               .arg(id, name, desc)
                               .arg(price, 0, 'f', 2)
                               .arg(stock);

        QListWidgetItem* item = new QListWidgetItem(itemText);
        item->setData(Qt::UserRole,     id);
        item->setData(Qt::UserRole + 1, name);
        item->setData(Qt::UserRole + 2, price);
        item->setData(Qt::UserRole + 3, desc);
        item->setData(Qt::UserRole + 4, stock);

        ui->searchResults->addItem(item);
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Cart
// ─────────────────────────────────────────────────────────────────────────────
void MainWindow::updateCartItemDisplay(QListWidgetItem* item)
{
    QString id       = item->data(Qt::UserRole).toString();
    QString name     = item->data(Qt::UserRole + 1).toString();
    double  price    = item->data(Qt::UserRole + 2).toDouble();
    int     quantity = item->data(Qt::UserRole + 5).toInt();
    int     stock    = item->data(Qt::UserRole + 4).toInt();

    item->setText(QString("%1 x%2 — ₱%3 each — stock:%4 — ID:%5")
                      .arg(name).arg(quantity)
                      .arg(price, 0, 'f', 2)
                      .arg(stock).arg(id));
}

void MainWindow::addToCart(QListWidgetItem* item)
{
    if (!item) return;

    QString id    = item->data(Qt::UserRole).toString();
    QString name  = item->data(Qt::UserRole + 1).toString();
    double  price = item->data(Qt::UserRole + 2).toDouble();
    int     stock = item->data(Qt::UserRole + 4).toInt();

    if (stock <= 0) {
        QMessageBox::warning(this, "Out of stock",
                             "This item is out of stock and cannot be added to the cart.");
        return;
    }

    // Check if the item is already in the cart
    QListWidgetItem* existing = nullptr;
    for (int i = 0; i < ui->cartList->count(); ++i) {
        QListWidgetItem* it = ui->cartList->item(i);
        if (it->data(Qt::UserRole).toString() == id) {
            existing = it;
            break;
        }
    }

    if (existing) {
        int quantity = existing->data(Qt::UserRole + 5).toInt() + 1;
        if (quantity > stock) {
            QMessageBox::warning(this, "Stock limit",
                                 QString("Only %1 unit(s) available.").arg(stock));
            return;
        }
        existing->setData(Qt::UserRole + 5, quantity);
        updateCartItemDisplay(existing);
    } else {
        QListWidgetItem* cartItem = new QListWidgetItem;
        cartItem->setData(Qt::UserRole,     id);
        cartItem->setData(Qt::UserRole + 1, name);
        cartItem->setData(Qt::UserRole + 2, price);
        cartItem->setData(Qt::UserRole + 4, stock);
        cartItem->setData(Qt::UserRole + 5, 1);
        updateCartItemDisplay(cartItem);
        ui->cartList->addItem(cartItem);
    }
    updateCartTotals();
}

void MainWindow::cartSelectionChanged(QListWidgetItem* current, QListWidgetItem*)
{
    bool hasItem = current != nullptr;
    ui->quantityBox->setEnabled(hasItem);
    ui->plusButton->setEnabled(hasItem);
    ui->minusButton->setEnabled(hasItem);
    ui->removeButton->setEnabled(hasItem);

    if (hasItem)
        ui->quantityBox->setValue(current->data(Qt::UserRole + 5).toInt());
}

void MainWindow::increaseQuantity()
{
    QListWidgetItem* current = ui->cartList->currentItem();
    if (!current) return;

    int stock    = current->data(Qt::UserRole + 4).toInt();
    int quantity = current->data(Qt::UserRole + 5).toInt() + 1;
    if (quantity > stock) {
        QMessageBox::warning(this, "Stock limit",
                             QString("Only %1 unit(s) available.").arg(stock));
        return;
    }
    current->setData(Qt::UserRole + 5, quantity);
    updateCartItemDisplay(current);
    ui->quantityBox->setValue(quantity);
    updateCartTotals();
}

void MainWindow::decreaseQuantity()
{
    QListWidgetItem* current = ui->cartList->currentItem();
    if (!current) return;

    int quantity = current->data(Qt::UserRole + 5).toInt() - 1;
    if (quantity <= 0) {
        delete current;
        updateCartTotals();
        return;
    }
    current->setData(Qt::UserRole + 5, quantity);
    updateCartItemDisplay(current);
    ui->quantityBox->setValue(quantity);
    updateCartTotals();
}

void MainWindow::quantityChanged(int value)
{
    QListWidgetItem* current = ui->cartList->currentItem();
    if (!current) return;

    int stock = current->data(Qt::UserRole + 4).toInt();
    if (value > stock) {
        QMessageBox::warning(this, "Stock limit",
                             QString("Only %1 unit(s) available.").arg(stock));
        ui->quantityBox->setValue(stock);
        value = stock;
    }
    current->setData(Qt::UserRole + 5, value);
    updateCartItemDisplay(current);
    updateCartTotals();
}

void MainWindow::updateCartTotals()
{
    double total = 0.0;
    for (int i = 0; i < ui->cartList->count(); ++i) {
        QListWidgetItem* item = ui->cartList->item(i);
        total += item->data(Qt::UserRole + 2).toDouble()
                 * item->data(Qt::UserRole + 5).toInt();
    }
    ui->totalLabel->setText(QString("Total: ₱%1").arg(total, 0, 'f', 2));
}

void MainWindow::removeFromCart()
{
    QListWidgetItem* current = ui->cartList->currentItem();
    if (current) {
        delete current;
        updateCartTotals();
    }
}

void MainWindow::clearCart()
{
    ui->cartList->clear();
    updateCartTotals();
    ui->quantityBox->setEnabled(false);
    ui->plusButton->setEnabled(false);
    ui->minusButton->setEnabled(false);
    ui->removeButton->setEnabled(false);
}

// ─────────────────────────────────────────────────────────────────────────────
// Checkout
// ─────────────────────────────────────────────────────────────────────────────
void MainWindow::checkout()
{
    if (ui->cartList->count() == 0) {
        QMessageBox::information(this, "Checkout", "Cart is empty.");
        return;
    }

    double total = 0.0;
    for (int i = 0; i < ui->cartList->count(); ++i) {
        QListWidgetItem* item = ui->cartList->item(i);
        total += item->data(Qt::UserRole + 2).toDouble()
                 * item->data(Qt::UserRole + 5).toInt();
    }

    QMessageBox::information(this, "Checkout",
                             QString("Total due: ₱%1\nSale complete.").arg(total, 0, 'f', 2));

    updateStock();
    ui->cartList->clear();
    updateCartTotals();
    ui->quantityBox->setEnabled(false);
    ui->plusButton->setEnabled(false);
    ui->minusButton->setEnabled(false);
    ui->removeButton->setEnabled(false);
    updateResults(ui->searchBox->text());
}

void MainWindow::updateStock()
{
    QSqlQuery update(db);
    update.prepare("UPDATE products SET stock = stock - :sold WHERE item_id = :id");

    for (int i = 0; i < ui->cartList->count(); ++i) {
        QListWidgetItem* item = ui->cartList->item(i);
        update.bindValue(":sold", item->data(Qt::UserRole + 5).toInt());
        update.bindValue(":id",   item->data(Qt::UserRole).toString());
        if (!update.exec())
            qWarning() << "Failed to update stock:" << update.lastError().text();
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Statistics
// ─────────────────────────────────────────────────────────────────────────────
void MainWindow::refreshStats()
{
    QSqlQuery query(db);

    if (query.exec("SELECT COUNT(*), SUM(retail_price * stock) FROM products") && query.next()) {
        ui->totalProductsLabel->setText(query.value(0).toString());
        double totalVal = query.value(1).toDouble();
        ui->totalValueLabel->setText(QString("₱%1").arg(totalVal, 0, 'f', 2));
    }

    ui->lowStockList->clear();
    query.prepare(
        "SELECT item_name, stock, item_id FROM products "
        "WHERE stock < 10 ORDER BY stock ASC");
    if (query.exec()) {
        while (query.next()) {
            QString name  = query.value(0).toString();
            int     stock = query.value(1).toInt();
            QString id    = query.value(2).toString();

            QListWidgetItem* item = new QListWidgetItem(
                QString("⚠️ %1 (ID: %2) — Only %3 left").arg(name, id).arg(stock));
            if (stock == 0)
                item->setForeground(Qt::red);
            ui->lowStockList->addItem(item);
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Import
// ─────────────────────────────────────────────────────────────────────────────
void MainWindow::importNewCsv()
{
    QString fileName = QFileDialog::getOpenFileName(
        this, "Import Medicines", "", "CSV Files (*.csv)");
    if (!fileName.isEmpty()) {
        Helpers::importCsvToDatabase(fileName, db);
        updateResults(ui->searchBox->text());
        QMessageBox::information(this, "Success", "Database updated successfully.");
    }
}
